//
// Created by baggyg on 02/04/2023.
//

#ifndef JKXR_VRTBDC_H
#define JKXR_VRTBDC_H

//VELOCITIES
#define TBDC_BRYAR_PISTOL_VEL      3300
#define TBDC_BLASTER_VELOCITY		4200
#define	TBDC_BOWCASTER_VELOCITY		3000
#define	TBDC_REPEATER_VELOCITY		3000
#define	TBDC_REPEATER_ALT_VELOCITY	1600
#define	TBDC_DEMP2_VELOCITY			2500
#define	TBDC_ROCKET_VELOCITY		2400

//FIRERATES
#define TBDC_BRYAR_PISTOL_FIRERATE  250
#define TBDC_BLASTER_FIRERATE       200

//SABERS
#define TBDC_SABER_BOUNCETIME       200
#define TBDC_SABER_BOUNCEANGLE       90

//SCALES
#define TBDC_SCALE_STOFFICER            102
#define TBDC_SCALE_STOFFICERALT         102
#define TBDC_SCALE_STCOMMANDER          103

#define TBDC_SCALE_IMPERIAL             101
#define TBDC_SCALE_IMPERIALOFFICER      102
#define TBDC_SCALE_IMPERIALCOMMANDER    103

#define TBDC_SCALE_REBORN               102
#define TBDC_SCALE_REBORNFORCEUSER      102
#define TBDC_SCALE_REBORNBOSS           103
#define TBDC_SCALE_REBORNACROBAT        102


#endif //JKXR_VRTBDC_H
