//
// Created by baggyg on 02/04/2023.
//

#ifndef JKXR_VRTBDC_H
#define JKXR_VRTBDC_H

//VELOCITIES
#define TBDC_BRYAR_PISTOL_VEL      3600
#define TBDC_BLASTER_VELOCITY		4600
#define	TBDC_BOWCASTER_VELOCITY		3000
#define	TBDC_REPEATER_VELOCITY		3200
#define	TBDC_REPEATER_ALT_VELOCITY	1600
#define	TBDC_DEMP2_VELOCITY			2500
#define	TBDC_ROCKET_VELOCITY		2800

//FIRERATES
#define TBDC_BRYAR_PISTOL_FIRERATE  250
#define TBDC_BLASTER_FIRERATE       200


#endif //JKXR_VRTBDC_H
