VERSION 1
CONFIG W:\bin\striped.cfg
ID 100
REFERENCE MENUS_VR
DESCRIPTION "VR Menu Localizations"
COUNT 160
INDEX 0
{
   REFERENCE COMMON_CONTROLS_ITEM
   TEXT_LANGUAGE1 "Common"
}
INDEX 1
{
   REFERENCE COMMON_CONTROLS_DESC
   TEXT_LANGUAGE1 "Common controls configuration."
}
INDEX 2
{
   REFERENCE WEAPON_CONTROLS_DESC
   TEXT_LANGUAGE1 "Weapon specific control configuration."
}
INDEX 3
{
   REFERENCE POWER_CONTROLS_DESC
   TEXT_LANGUAGE1 "Force Power specific control configuration."
}
INDEX 4
{
   REFERENCE INVENTORY_CONTROLS_DESC
   TEXT_LANGUAGE1 "Inventory specific control configuration."
}
INDEX 5
{
   REFERENCE COMFORT_CONTROLS_ITEM
   TEXT_LANGUAGE1 "Comfort"
}
INDEX 6
{
   REFERENCE COMFORT_CONTROLS_DESC
   TEXT_LANGUAGE1 "Configure comfort options."
}
INDEX 7
{
   REFERENCE MOVEMENT_SPEED_ITEM
   TEXT_LANGUAGE1 "OBSOLETE Movement Speed:"
}
INDEX 8
{
   REFERENCE MOVEMENT_SPEED_DESC
   TEXT_LANGUAGE1 "OBSOLETE Sets player movement speed."
}
INDEX 9
{
   REFERENCE DIRECTION_MODE_ITEM
   TEXT_LANGUAGE1 "Direction Mode:"
}
INDEX 10
{
   REFERENCE DIRECTION_MODE_DESC
   TEXT_LANGUAGE1 "Choose movement direction mode."
}
INDEX 11
{
   REFERENCE DIRECTION_MODE_CONTROLLER
   TEXT_LANGUAGE1 "Off-hand Controller"
}
INDEX 12
{
   REFERENCE DIRECTION_MODE_HMD
   TEXT_LANGUAGE1 "HMD"
}
INDEX 13
{
   REFERENCE SMOOTH_TURN_ITEM
   TEXT_LANGUAGE1 "Smooth turn:"
}
INDEX 14
{
   REFERENCE SMOOTH_TURN_DESC
   TEXT_LANGUAGE1 "Enables or disables smooth turning."
}
INDEX 15
{
   REFERENCE SMOOTH_TURN_3RD_PERSON
   TEXT_LANGUAGE1 "3rd Person"
}
INDEX 16
{
   REFERENCE TURN_ANGLE_ITEM
   TEXT_LANGUAGE1 "Turn Angle:"
}
INDEX 17
{
   REFERENCE TURN_ANGLE_DESC
   TEXT_LANGUAGE1 "Degrees to turn when using snap turn / Speed of smooth turn."
}
INDEX 18
{
   REFERENCE TURN_ANGLE_30DEGREES
   TEXT_LANGUAGE1 "30 Degrees"
}
INDEX 19
{
   REFERENCE TURN_ANGLE_45DEGREES
   TEXT_LANGUAGE1 "45 Degrees"
}
INDEX 20
{
   REFERENCE TURN_ANGLE_90DEGREES
   TEXT_LANGUAGE1 "90 Degrees"
}
INDEX 21
{
   REFERENCE SWITCH_STICKS_ITEM
   TEXT_LANGUAGE1 "Switch Sticks:"
}
INDEX 22
{
   REFERENCE SWITCH_STICKS_DESC
   TEXT_LANGUAGE1 "Switches left/right controller thubmsticks."
}
INDEX 23
{
   REFERENCE LEFT_HANDED_ITEM
   TEXT_LANGUAGE1 "Left-Handed Mode:"
}
INDEX 24
{
   REFERENCE LEFT_HANDED_DESC
   TEXT_LANGUAGE1 "Enables left-handed mode."
}
INDEX 25
{
   REFERENCE WEAPON_PITCH_ITEM
   TEXT_LANGUAGE1 "Weapon Pitch:"
}
INDEX 26
{
   REFERENCE WEAPON_PITCH_DESC
   TEXT_LANGUAGE1 "Sets aiming pitch of held weapon."
}
INDEX 27
{
   REFERENCE TWO_HANDED_ITEM
   TEXT_LANGUAGE1 "Two-Handed Mode:"
}
INDEX 28
{
   REFERENCE TWO_HANDED_DESC
   TEXT_LANGUAGE1 "Enables two-handed weapon handling."
}
INDEX 29
{
   REFERENCE GUN_STOCK_ITEM
   TEXT_LANGUAGE1 "Virtual Gun Stock:"
}
INDEX 30
{
   REFERENCE GUN_STOCK_DESC
   TEXT_LANGUAGE1 "Enables or disables virtual gun stock. Requires two-handed mode to be enabled."
}
INDEX 31
{
   REFERENCE FORCE_POWER_DIRECTION_ITEM
   TEXT_LANGUAGE1 "OBSOLETE Force Power Direction Hint:"
}
INDEX 32
{
   REFERENCE FORCE_POWER_DIRECTION_DESC
   TEXT_LANGUAGE1 "OBSOLETE Hint as to which direction a force power was fired."
}
INDEX 33
{
   REFERENCE FORCE_SPEED_FOV_ITEM
   TEXT_LANGUAGE1 "Force Speed FOV Change:"
}
INDEX 34
{
   REFERENCE FORCE_SPEED_FOV_DESC
   TEXT_LANGUAGE1 "Whether the FOV will be adjusted briefly when engaging Force Speed."
}
INDEX 35
{
   REFERENCE IMMERSIVE_CINEMATICS_ITEM
   TEXT_LANGUAGE1 "Immersive Cinematics:"
}
INDEX 36
{
   REFERENCE IMMERSIVE_CINEMATICS_DESC
   TEXT_LANGUAGE1 "Enables or disables immersive cinematics."
}
INDEX 37
{
   REFERENCE SCREEN_DISTANCE_ITEM
   TEXT_LANGUAGE1 "Menu Screen Distance:"
}
INDEX 38
{
   REFERENCE SCREEN_DISTANCE_DESC
   TEXT_LANGUAGE1 "Select menu screen distance."
}
INDEX 39
{
   REFERENCE SCREEN_DISTANCE_NEAR
   TEXT_LANGUAGE1 "Near"
}
INDEX 40
{
   REFERENCE SCREEN_DISTANCE_MEDIUM
   TEXT_LANGUAGE1 "Medium"
}
INDEX 41
{
   REFERENCE SCREEN_DISTANCE_FAR
   TEXT_LANGUAGE1 "Far"
}
INDEX 42
{
   REFERENCE HEIGHT_ADJUST_ITEM
   TEXT_LANGUAGE1 "Height Adjust:"
}
INDEX 43
{
   REFERENCE HEIGHT_ADJUST_DESC
   TEXT_LANGUAGE1 "Adjusts your in-game height."
}
INDEX 44
{
   REFERENCE DIFFICULTY_SETUP_ITEM
   TEXT_LANGUAGE1 "Difficulty"
}
INDEX 45
{
   REFERENCE DIFFICULTY_SETUP_DESC
   TEXT_LANGUAGE1 "Various gameplay difficulty tweaks."
}
INDEX 46
{
   REFERENCE MODEL_DISMEMBERMENT_DISABLED
   TEXT_LANGUAGE1 "Disabled"
}
INDEX 47
{
   REFERENCE MODEL_DISMEMBERMENT_MILD
   TEXT_LANGUAGE1 "Mild"
}
INDEX 48
{
   REFERENCE MODEL_DISMEMBERMENT_BEARABLE
   TEXT_LANGUAGE1 "Bearable"
}
INDEX 49
{
   REFERENCE MODEL_DISMEMBERMENT_UNSETTLING
   TEXT_LANGUAGE1 "Unsettling"
}
INDEX 50
{
   REFERENCE DISMEMBERMENT_PROBABILITY_OFTEN
   TEXT_LANGUAGE1 "Often"
}
INDEX 51
{
   REFERENCE DISMEMBERMENT_PROBABILITY_ALWAYS
   TEXT_LANGUAGE1 "Always"
}
INDEX 52
{
   REFERENCE LASER_AUTODEFLECTING_ITEM
   TEXT_LANGUAGE1 "Laser Auto Deflecting:"
}
INDEX 53
{
   REFERENCE LASER_AUTODEFLECTING_DESC
   TEXT_LANGUAGE1 "Enables or disables 1st person auto deflecting of lasers with lightsabers."
}
INDEX 54
{
   REFERENCE SABER_AUTOBLOCKING_ITEM
   TEXT_LANGUAGE1 "OBSOLETE Lightsaber Auto Blocking:"
}
INDEX 55
{
   REFERENCE SABER_AUTOBLOCKING_DESC
   TEXT_LANGUAGE1 "OBSOLETE Enables or disables auto blocking of enemy lightsaber."
}
INDEX 56
{
   REFERENCE SABER_REALISM_ITEM
   TEXT_LANGUAGE1 "Lightsaber Realism:"
}
INDEX 57
{
   REFERENCE SABER_REALISM_DESC
   TEXT_LANGUAGE1 "Choose effectivity of lightsaber. Affects lightsaber duels difficulty mostly."
}
INDEX 58
{
   REFERENCE SABER_REALISM_DEFAULT
   TEXT_LANGUAGE1 "Default"
}
INDEX 59
{
   REFERENCE SABER_REALISM_INCREASED
   TEXT_LANGUAGE1 "Increased Damage"
}
INDEX 60
{
   REFERENCE SABER_REALISM_CRITICAL
   TEXT_LANGUAGE1 "Fatal Critical Hit"
}
INDEX 61
{
   REFERENCE SABER_REALISM_INSTANT
   TEXT_LANGUAGE1 "Instant Kill"
}
INDEX 62
{
   REFERENCE FENCING_SPEED_ITEM
   TEXT_LANGUAGE1 "Enemy Fencing Speed:"
}
INDEX 63
{
   REFERENCE FENCING_SPEED_DESC
   TEXT_LANGUAGE1 "Choose fencing swiftness of enemies. Affects lightsaber duels difficulty."
}
INDEX 64
{
   REFERENCE FENCING_SPEED_SLOWER
   TEXT_LANGUAGE1 "Slower"
}
INDEX 65
{
   REFERENCE FENCING_SPEED_DEFAULT
   TEXT_LANGUAGE1 "Default"
}
INDEX 66
{
   REFERENCE FENCING_SPEED_FASTER
   TEXT_LANGUAGE1 "Faster"
}
INDEX 67
{
   REFERENCE GAME_DIFFICULTY_ITEM
   TEXT_LANGUAGE1 "Game Difficulty:"
}
INDEX 68
{
   REFERENCE GAME_DIFFICULTY_DESC
   TEXT_LANGUAGE1 "Change game difficulty."
}
INDEX 69
{
   REFERENCE CHEATS_TITLE
   TEXT_LANGUAGE1 "May the force be with you..."
}
INDEX 70
{
   REFERENCE CHEATS_GIVE_HEALTH_ITEM
   TEXT_LANGUAGE1 "Replenish Health"
}
INDEX 71
{
   REFERENCE CHEATS_GIVE_HEALTH_DESC
   TEXT_LANGUAGE1 "Replenishes health."
}
INDEX 72
{
   REFERENCE CHEATS_GIVE_ARMOR_ITEM
   TEXT_LANGUAGE1 "Replenish Armor"
}
INDEX 73
{
   REFERENCE CHEATS_GIVE_ARMOR_DESC
   TEXT_LANGUAGE1 "Replenishes armor."
}
INDEX 74
{
   REFERENCE CHEATS_GIVE_AMMO_ITEM
   TEXT_LANGUAGE1 "Replenish Ammo"
}
INDEX 75
{
   REFERENCE CHEATS_GIVE_AMMO_DESC
   TEXT_LANGUAGE1 "Replenishes ammunition."
}
INDEX 76
{
   REFERENCE CHEATS_GIVE_BATTERIES_ITEM
   TEXT_LANGUAGE1 "Replenish Batteries"
}
INDEX 77
{
   REFERENCE CHEATS_GIVE_BATTERIES_DESC
   TEXT_LANGUAGE1 "Replenishes batteries."
}
INDEX 78
{
   REFERENCE CHEATS_GIVE_SABER_ITEM
   TEXT_LANGUAGE1 "Give Lightsaber"
}
INDEX 79
{
   REFERENCE CHEATS_GIVE_SABER_DESC
   TEXT_LANGUAGE1 "Gives only lighsaber (with powers to use it)."
}
INDEX 80
{
   REFERENCE CHEATS_GIVE_WEAPONS_ITEM
   TEXT_LANGUAGE1 "Give All Weapons"
}
INDEX 81
{
   REFERENCE CHEATS_GIVE_WEAPONS_DESC
   TEXT_LANGUAGE1 "Gives all weapons (including powers to use lightsaber)."
}
INDEX 82
{
   REFERENCE CHEATS_GIVE_ITEMS_ITEM
   TEXT_LANGUAGE1 "Give All Items"
}
INDEX 83
{
   REFERENCE CHEATS_GIVE_ITEMS_DESC
   TEXT_LANGUAGE1 "Gives all inventory items."
}
INDEX 84
{
   REFERENCE CHEATS_GIVE_POWERS_ITEM
   TEXT_LANGUAGE1 "Unlock All Powers"
}
INDEX 85
{
   REFERENCE CHEATS_GIVE_POWERS_DESC
   TEXT_LANGUAGE1 "Unlocks all force powers."
}
INDEX 86
{
   REFERENCE CHEATS_SABER_COLOR_TITLE
   TEXT_LANGUAGE1 "Lightsaber Color:"
}
INDEX 87
{
   REFERENCE CHEATS_SABER_COLOR_BLUE_ITEM
   TEXT_LANGUAGE1 "Blue"
}
INDEX 88
{
   REFERENCE CHEATS_SABER_COLOR_BLUE_DESC
   TEXT_LANGUAGE1 "Use blue lightsaber."
}
INDEX 89
{
   REFERENCE CHEATS_SABER_COLOR_GREEN_ITEM
   TEXT_LANGUAGE1 "Green"
}
INDEX 90
{
   REFERENCE CHEATS_SABER_COLOR_GREEN_DESC
   TEXT_LANGUAGE1 "Use green lightsaber."
}
INDEX 91
{
   REFERENCE CHEATS_SABER_COLOR_RED_ITEM
   TEXT_LANGUAGE1 "Red"
}
INDEX 92
{
   REFERENCE CHEATS_SABER_COLOR_RED_DESC
   TEXT_LANGUAGE1 "Use red lightsaber."
}
INDEX 93
{
   REFERENCE CHEATS_SABER_COLOR_ORANGE_ITEM
   TEXT_LANGUAGE1 "Orange"
}
INDEX 94
{
   REFERENCE CHEATS_SABER_COLOR_ORANGE_DESC
   TEXT_LANGUAGE1 "Use orange lightsaber."
}
INDEX 95
{
   REFERENCE CHEATS_SABER_COLOR_PURPLE_ITEM
   TEXT_LANGUAGE1 "Purple"
}
INDEX 96
{
   REFERENCE CHEATS_SABER_COLOR_PURPLE_DESC
   TEXT_LANGUAGE1 "Use purple lightsaber."
}
INDEX 97
{
   REFERENCE CHEATS_ITEM
   TEXT_LANGUAGE1 "CHEATS"
}
INDEX 98
{
   REFERENCE CHEATS_SABER_MARK_COOL_DOWN_TITLE
   TEXT_LANGUAGE1 "Lightsaber Burn Marks Cool Down:"
}
INDEX 99
{
   REFERENCE CHEATS_SABER_MARK_COOL_DOWN_DESC
   TEXT_LANGUAGE1 "Set how long it takes for burn marks to cool down."
}
INDEX 100
{
   REFERENCE WEAPON_CROSSHAIR_ITEM
   TEXT_LANGUAGE1 "Weapon Crosshair:"
}
INDEX 101
{
   REFERENCE WEAPON_CROSSHAIR_DESC
   TEXT_LANGUAGE1 "Select style of weapon crosshair or disable it."
}
INDEX 102
{
   REFERENCE FORCE_CROSSHAIR_ITEM
   TEXT_LANGUAGE1 "Force Power Crosshair:"
}
INDEX 103
{
   REFERENCE FORCE_CROSSHAIR_DESC
   TEXT_LANGUAGE1 "Select style of force power crosshair or disable it."
}
INDEX 104
{
   REFERENCE OVERWRITE_GAME_ITEM
   TEXT_LANGUAGE1 "OVERWRITE GAME"
}
INDEX 105
{
   REFERENCE OVERWRITE_GAME_DESC
   TEXT_LANGUAGE1 "Overwrite chosen game."
}
INDEX 106
{
   REFERENCE WEAPON_VELOCITY_TRIGGER_ITEM
   TEXT_LANGUAGE1 "Melee Trigger Speed:"
}
INDEX 107
{
   REFERENCE WEAPON_VELOCITY_TRIGGER_DESC
   TEXT_LANGUAGE1 "Adjust how fast to move hand to trigger melee attack."
}
INDEX 108
{
   REFERENCE FORCE_MOTION_TRIGGER_TOGGLE_ITEM
   TEXT_LANGUAGE1 "Gesture Triggered Force:"
}
INDEX 109
{
   REFERENCE FORCE_MOTION_TRIGGER_TOGGLE_DESC
   TEXT_LANGUAGE1 "Toggles triggering of force powers by gesture."
}
INDEX 110
{
   REFERENCE FORCE_VELOCITY_TRIGGER_ITEM
   TEXT_LANGUAGE1 "Force Trigger Speed:"
}
INDEX 111
{
   REFERENCE FORCE_VELOCITY_TRIGGER_DESC
   TEXT_LANGUAGE1 "Adjust how fast to move hand to trigger force power."
}
INDEX 112
{
   REFERENCE CROUCH_TOGGLE_ITEM
   TEXT_LANGUAGE1 "Crouch Toggle:"
}
INDEX 113
{
   REFERENCE CROUCH_TOGGLE_DESC
   TEXT_LANGUAGE1 "Turn on to enable crouch toggle."
}
INDEX 114
{
   REFERENCE CROUCH_IRL_ITEM
   TEXT_LANGUAGE1 "IRL Crouch:"
}
INDEX 115
{
   REFERENCE CROUCH_IRL_DESC
   TEXT_LANGUAGE1 "Crouch IRL to crouch in game (use crouch button to recalibrate standing height)."
}
INDEX 116
{
   REFERENCE CROUCH_IRL_1ST_PERSON
   TEXT_LANGUAGE1 "1st Person"
}
INDEX 117
{
   REFERENCE AUTO_USE_BACTA_ITEM
   TEXT_LANGUAGE1 "Auto Use Bacta:"
}
INDEX 118
{
   REFERENCE AUTO_USE_BACTA_DESC
   TEXT_LANGUAGE1 "When enabled, automatically uses bacta canister before dying."
}
INDEX 119
{
   REFERENCE HAPTIC_INTENSITY_ITEM
   TEXT_LANGUAGE1 "Haptic Intensity:"
}
INDEX 120
{
   REFERENCE HAPTIC_INTENSITY_DESC
   TEXT_LANGUAGE1 "Adjust intensity of haptic feedback."
}
INDEX 121
{
   REFERENCE COMFORT_VIGNETTE_ITEM
   TEXT_LANGUAGE1 "Comfort Vignette:"
}
INDEX 122
{
   REFERENCE COMFORT_VIGNETTE_DESC
   TEXT_LANGUAGE1 "Adjust size of comfort vignette."
}
INDEX 123
{
   REFERENCE SABER_3RD_PERSON_ITEM
   TEXT_LANGUAGE1 "3rd Person Lightsaber:"
}
INDEX 124
{
   REFERENCE SABER_3RD_PERSON_DESC
   TEXT_LANGUAGE1 "Choose whether to swith to 3rd person when using lightsaber."
}
INDEX 125
{
   REFERENCE SABER_3RD_PERSON_DISABLED
   TEXT_LANGUAGE1 "Disabled"
}
INDEX 126
{
   REFERENCE SABER_3RD_PERSON_MANUAL
   TEXT_LANGUAGE1 "Manual"
}
INDEX 127
{
   REFERENCE SABER_3RD_PERSON_AUTO
   TEXT_LANGUAGE1 "Auto"
}
INDEX 128
{
   REFERENCE GESTURE_TRIGGERED_USE_ITEM
   TEXT_LANGUAGE1 "Gesture Triggered Use:"
}
INDEX 129
{
   REFERENCE GESTURE_TRIGGERED_USE_DESC
   TEXT_LANGUAGE1 "Toggles triggering of use/action by gesture (not active in 3rd person)."
}
INDEX 130
{
   REFERENCE GESTURE_TRIGGERED_USE_OFF_HAND
   TEXT_LANGUAGE1 "Off-Hand"
}
INDEX 131
{
   REFERENCE GESTURE_TRIGGERED_USE_DOMINANT_HAND
   TEXT_LANGUAGE1 "Dominant-Hand"
}
INDEX 132
{
   REFERENCE USE_GESTURE_BOUNDARY_ITEM
   TEXT_LANGUAGE1 "Use Gesture Boundary:"
}
INDEX 133
{
   REFERENCE USE_GESTURE_BOUNDARY_DESC
   TEXT_LANGUAGE1 "Configures how far you need to reach to activate use gesture."
}
INDEX 134
{
   REFERENCE DIRECTORS_CUT_ITEM
   TEXT_LANGUAGE1 "Team Beef Director's Cut:"
}
INDEX 135
{
   REFERENCE DIRECTORS_CUT_DESC
   TEXT_LANGUAGE1 "Various tweaks for better balance of VR gameplay."
}
INDEX 136
{
   REFERENCE HUD_SCALE_ITEM
   TEXT_LANGUAGE1 "VR HUD Scale:"
}
INDEX 137
{
   REFERENCE HUD_SCALE_DESC
   TEXT_LANGUAGE1 "Scale of the HUD in VR."
}
INDEX 138
{
   REFERENCE HUD_STEREO_ITEM
   TEXT_LANGUAGE1 "VR HUD Stereo:"
}
INDEX 139
{
   REFERENCE HUD_STEREO_DESC
   TEXT_LANGUAGE1 "Stereo depth of the HUD in VR."
}
INDEX 140
{
   REFERENCE HUD_YOFFSET_ITEM
   TEXT_LANGUAGE1 "VR HUD Y-Offset:"
}
INDEX 141
{
   REFERENCE HUD_YOFFSET_DESC
   TEXT_LANGUAGE1 "Y-Offset of the HUD in VR."
}
INDEX 142
{
   REFERENCE USABLE_OBJECT_HINT_ITEM
   TEXT_LANGUAGE1 "Usable Objects Hint:"
}
INDEX 143
{
   REFERENCE USABLE_OBJECT_HINT_DESC
   TEXT_LANGUAGE1 "Show icon when looking at objects that can be used."
}
INDEX 144
{
   REFERENCE HELP_BUTTON_ITEM
   TEXT_LANGUAGE1 "JKXR Help"
}
INDEX 145
{
   REFERENCE HELP_BUTTON_DESC
   TEXT_LANGUAGE1 "Short tutorials explaining various game mechanics."
}
INDEX 146
{
   REFERENCE TUTORIAL_VIDEO_1
   TEXT_LANGUAGE1 "How to quick save / load"
}
INDEX 147
{
   REFERENCE TUTORIAL_VIDEO_2
   TEXT_LANGUAGE1 "How to use weapon scopes"
}
INDEX 148
{
   REFERENCE TUTORIAL_VIDEO_3
   TEXT_LANGUAGE1 "How to use inventory items"
}
INDEX 149
{
   REFERENCE TUTORIAL_VIDEO_4
   TEXT_LANGUAGE1 "How to throw the saber"
}
INDEX 150
{
   REFERENCE TUTORIAL_VIDEO_5
   TEXT_LANGUAGE1 "How to activate useable things"
}
INDEX 151
{
   REFERENCE TUTORIAL_VIDEO_6
   TEXT_LANGUAGE1 "How to use force gesture"
}
INDEX 152
{
   REFERENCE TUTORIAL_VIDEO_7
   TEXT_LANGUAGE1 "How to use the weapons / force wheel"
}
INDEX 153
{
   REFERENCE TUTORIAL_VIDEO_8
   TEXT_LANGUAGE1 "Introduction to lightsaber duels"
}
INDEX 154
{
   REFERENCE CONTROL_SCHEME_HELP
   TEXT_LANGUAGE1 "Default control scheme"
}
INDEX 155
{
   REFERENCE MODS_BUTTON_DESC
   TEXT_LANGUAGE1 "Load custom mods."
}
INDEX 156
{
   REFERENCE MODS_WARNING_TEXT_1
   TEXT_LANGUAGE1 "We recommend"
}
INDEX 157
{
   REFERENCE MODS_WARNING_TEXT_2
   TEXT_LANGUAGE1 "the JKXR Companion App"
}
INDEX 158
{
   REFERENCE MODS_WARNING_TEXT_3
   TEXT_LANGUAGE1 "to download and launch mods."
}
INDEX 159
{
   REFERENCE MODS_WARNING_CONFIRM
   TEXT_LANGUAGE1 "Continue"
}
